////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  Copyright (C) 2025, CryptoLab, Inc.                                       //
//                                                                            //
//  Licensed under the Apache License, Version 2.0 (the "License");           //
//  you may not use this file except in compliance with the License.          //
//  You may obtain a copy of the License at                                   //
//                                                                            //
//     http://www.apache.org/licenses/LICENSE-2.0                             //
//                                                                            //
//  Unless required by applicable law or agreed to in writing, software       //
//  distributed under the License is distributed on an "AS IS" BASIS,         //
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  //
//  See the License for the specific language governing permissions and       //
//  limitations under the License.                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//
// EVIS v1 fixture round-trip tests.
//
// Loads keypack files generated by the **pre-refactor** main HEAD (commit
// 5ca3023d, "Revert fat lib (#670)") and verifies that the post-refactor
// PRIME_Q/P scalars -> PRIMES_Q[]/PRIMES_P[] arrays code path can still
// deserialize them and run a basic encrypt/decrypt operation.
//
// This is a binary-level regression guard for the EVIS v1 wire format. The
// static_asserts in SerializationRoundTripTest.cpp::EvisV1PrimeArrayCompat
// verify the legacy scalar aliases at compile time; this test verifies the
// runtime load + use path against captured pre-refactor key bytes.
//
// See crypto/test/fixtures/evis-v1/README.md for the fixture provenance,
// generation procedure, and known coverage gaps (e.g. MMS keypack size).
//
////////////////////////////////////////////////////////////////////////////////

#include <gtest/gtest.h>

#include <filesystem>
#include <string>
#include <vector>

#include "EVI/Const.hpp"
#include "EVI/impl/DecryptorImpl.hpp"
#include "EVI/impl/EncryptorImpl.hpp"
#include "EVI/impl/KeyGeneratorImpl.hpp"
#include "EVI/impl/SecretKeyImpl.hpp"
#include "utils.hpp"

using namespace evi::detail;
namespace fs = std::filesystem;

namespace {

// Anchored at $EVIS_V1_FIXTURE_DIR/<preset>_<flow>/ when the env var is set
// (CI fetches the fixture bundle from gs://envector-qa/evi/fixtures/evis-v1/v1/
// into a temp dir and exports the var), otherwise at the in-tree download dir
// crypto/test/fixtures/evis-v1/v1/<preset>_<flow>/ that fetch.sh populates.
fs::path fixtureDir(const std::string &fixture_name) {
    if (const char *env = std::getenv("EVIS_V1_FIXTURE_DIR"); env != nullptr && *env != '\0') {
        return fs::path(env) / fixture_name;
    }
    return fs::path(EVI_PROJECT_ROOT) / "test" / "fixtures" / "evis-v1" / "v1" / fixture_name;
}

struct FixtureSpec {
    std::string name; // directory under crypto/test/fixtures/evis-v1/
    evi::ParameterPreset preset;
    evi::EvalMode mode;
    std::string description;
};

// RMP fixtures cover the four production presets. MMS coverage is intentionally
// not bundled here — see fixtures/evis-v1/README.md for the size-budget reason
// and the alternative coverage path (KeyValidationTest::EvalKeySharedAMMSSaveLoad
// runs an in-process MMS save->load round trip on every CI run).
const std::vector<FixtureSpec> kFixtures = {
    {"IP0_RMP", evi::ParameterPreset::IP0, evi::EvalMode::RMP, "IP0 RMP (51b chain + 55b aux)"},
    {"IP1_RMP", evi::ParameterPreset::IP1, evi::EvalMode::RMP, "IP1 RMP (35b/35b chain + 39b aux)"},
    {"IP2_RMP", evi::ParameterPreset::IP2, evi::EvalMode::RMP, "IP2 RMP (32b/32b chain + 43b aux, u32-eligible)"},
    {"QF0_RMP", evi::ParameterPreset::QF0, evi::EvalMode::RMP, "QF0 RMP (58b chain + 51b aux)"},
};

// Use the smallest production rank (32 = MIN_CONTEXT_SIZE). Pre-refactor
// MultiKeyGenerator with EvalMode=RMP saves a per-rank EVIKeysNN.bin inside
// the EvalKey.bin container; rank=32 is always present.
constexpr u32 kFixtureRank = 32;

// Class fixture so test names show up grouped in ctest output.
class EvisV1FixtureLoadTest : public ::testing::TestWithParam<FixtureSpec> {};

} // namespace

// ============================================================================
// Test 1: load completes without throwing.
//
// Confirms that the EVIS v1 byte layout produced by pre-refactor code is still
// a valid input for the post-refactor KeyPackImpl::loadEvalKeyFile(). Failure
// here is the signature of an EVIS-v1 wire-format break (e.g. the legacy
// scalar aliases got accidentally rebound to a different prime when the
// derived constants were array-ified).
// ============================================================================
TEST_P(EvisV1FixtureLoadTest, LoadEvalAndEncKey) {
    const FixtureSpec &spec = GetParam();
    const fs::path dir = fixtureDir(spec.name);
    ASSERT_TRUE(fs::exists(dir)) << "Missing fixture directory: " << dir;
    ASSERT_TRUE(fs::exists(dir / "EvalKey.bin")) << "Missing EvalKey.bin under " << dir;
    ASSERT_TRUE(fs::exists(dir / "EncKey.bin")) << "Missing EncKey.bin under " << dir;
    ASSERT_TRUE(fs::exists(dir / "SecKey.bin")) << "Missing SecKey.bin under " << dir;

    Context context = makeContext(spec.preset, evi::DeviceType::CPU, kFixtureRank, spec.mode);
    KeyPack pack = makeKeyPack(context);

    EXPECT_NO_THROW(pack->loadEvalKeyFile((dir / "EvalKey.bin").string()))
        << "loadEvalKeyFile threw for " << spec.description;
    EXPECT_NO_THROW(pack->loadEncKeyFile((dir / "EncKey.bin").string()))
        << "loadEncKeyFile threw for " << spec.description;
}

// ============================================================================
// Test 2: encrypt/decrypt round-trip with the loaded keys.
//
// "Run a small operation on the loaded key" per refactor plan. Loads EncKey +
// SecKey from the fixture, encrypts a deterministic plaintext, decrypts, and
// asserts the recovered values match the input. A wire-format break that
// silently corrupts coefficients (rather than throwing on load) would surface
// here as a precision blow-up.
//
// EncDec is independent of EvalKey, but a fixture without an intact EncKey
// header would already have failed Test 1. We use SecKey.bin directly via
// SecretKeyData(path) — the same path SecretKey load path used in production
// (e.g. envector-msa shaper key cache).
// ============================================================================
TEST_P(EvisV1FixtureLoadTest, EncryptDecryptRoundTrip) {
    const FixtureSpec &spec = GetParam();
    const fs::path dir = fixtureDir(spec.name);
    ASSERT_TRUE(fs::exists(dir)) << "Missing fixture directory: " << dir;

    Context context = makeContext(spec.preset, evi::DeviceType::CPU, kFixtureRank, spec.mode);
    KeyPack pack = makeKeyPack(context);
    pack->loadEncKeyFile((dir / "EncKey.bin").string());

    // Deterministic plaintext (no RNG dependency on the fixture).
    std::vector<float> msg(DEGREE, 0);
    for (u32 i = 0; i < kFixtureRank; ++i) {
        // Bounded magnitude (|x| <= 1) so RMP-mode encoding error stays well
        // below the 1/64 tolerance applied across the rest of the test suite.
        msg[i] = (i % 2 == 0) ? 0.25f : -0.25f;
    }

    Encryptor enc = makeEncryptor(context, pack);
    Decryptor dec = makeDecryptor(context);

    SecretKey sec_key = std::make_shared<SecretKeyData>((dir / "SecKey.bin").string());

    auto query = enc->encrypt(msg, evi::EncodeType::ITEM);
    auto dmsg = dec->decrypt(query, sec_key);

    constexpr double kMaxError = 1.0 / 16.0;
    double max_err = 0.0;
    for (u32 i = 0; i < kFixtureRank; ++i) {
        max_err = std::max(max_err, std::abs(static_cast<double>(dmsg[i] - msg[i])));
    }
    EXPECT_LE(max_err, kMaxError) << "Encrypt->decrypt round-trip exceeded " << kMaxError << " for fixture "
                                  << spec.description;
}

INSTANTIATE_TEST_SUITE_P(EvisV1, EvisV1FixtureLoadTest, ::testing::ValuesIn(kFixtures),
                         [](const ::testing::TestParamInfo<FixtureSpec> &info) {
                             return info.param.name;
                         });
