////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  Copyright (C) 2025, CryptoLab, Inc.                                       //
//                                                                            //
//  Licensed under the Apache License, Version 2.0 (the "License");           //
//  you may not use this file except in compliance with the License.          //
//  You may obtain a copy of the License at                                   //
//                                                                            //
//     http://www.apache.org/licenses/LICENSE-2.0                             //
//                                                                            //
//  Unless required by applicable law or agreed to in writing, software       //
//  distributed under the License is distributed on an "AS IS" BASIS,         //
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  //
//  See the License for the specific language governing permissions and       //
//  limitations under the License.                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "test_utils.h"
#include "unity.h"

#include "evi_c/context.h"
#include "evi_c/keypack.h"

#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

static const char *kEncKeyName = "EncKey.bin";
static const char *kEvalKeyName = "EvalKey.bin";

void test_keypack_create(void) {
    evi_context_t *context = NULL;
    evi_keypack_t *pack = NULL;

    evi_status_t status =
        evi_context_create(EVI_PARAMETER_PRESET_IP0, EVI_DEVICE_TYPE_CPU, 128, EVI_EVAL_MODE_RMP, NULL, &context);
    TEST_ASSERT_EQUAL(EVI_STATUS_SUCCESS, status);
    TEST_ASSERT_NOT_NULL(context);

    status = evi_keypack_create(context, &pack);
    TEST_ASSERT_EQUAL(EVI_STATUS_SUCCESS, status);
    TEST_ASSERT_NOT_NULL(pack);

    evi_keypack_destroy(pack);
    evi_context_destroy(context);
}

void test_keypack_create_from_path(void) {
    static const char *dir = "./tmp_keypack_test";
    make_directory(dir);
    evi_context_t *context = NULL;
    evi_keypack_t *pack = NULL;

    TEST_ASSERT_EQUAL(EVI_STATUS_SUCCESS, evi_context_create(EVI_PARAMETER_PRESET_IP0, EVI_DEVICE_TYPE_CPU, 128,
                                                             EVI_EVAL_MODE_FLAT, NULL, &context));
    TEST_ASSERT_NOT_NULL(context);

    char enc_path[PATH_MAX];
    char eval_path[PATH_MAX];
    snprintf(enc_path, sizeof(enc_path), "%s/%s", dir, kEncKeyName);
    snprintf(eval_path, sizeof(eval_path), "%s/%s", dir, kEvalKeyName);

    struct stat st;
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, stat(enc_path, &st), "expected EncKey.bin generated by keygenerator test");
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, stat(eval_path, &st), "expected EvalKey.bin generated by keygenerator test");

    TEST_ASSERT_EQUAL(EVI_STATUS_SUCCESS, evi_keypack_create(context, &pack));
    TEST_ASSERT_NOT_NULL(pack);

    TEST_ASSERT_EQUAL(EVI_STATUS_SUCCESS, evi_keypack_load_enc_key(pack, enc_path));
    TEST_ASSERT_EQUAL(EVI_STATUS_SUCCESS, evi_keypack_load_eval_key(pack, eval_path));

    evi_keypack_destroy(pack);
    evi_context_destroy(context);

    remove_directory(dir);
}
